"""add name and size fields to files table

Revision ID: 8b676e93c8df
Revises: d7e3c4b44fee
Create Date: 2026-07-30 00:02:45.356873

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b676e93c8df"
down_revision: Union[str, Sequence[str], None] = "d7e3c4b44fee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("name", sa.String(length=40), nullable=False))
    op.add_column("files", sa.Column("size", sa.Integer(), nullable=False))
    op.create_check_constraint(
        "length_file_name",
        "files",
        """
                LENGTH(name) >= 3
                AND LENGTH(name) <= 40
                """,
    )
    op.create_check_constraint(
        "value_size",
        "files",
        """
                size > 0
                AND size <= 1 * 1024 * 1024
                """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("length_file_name", "files", type_="check")
    op.drop_constraint("value_size", "files", type_="check")
    op.drop_column("files", "size")
    op.drop_column("files", "name")
    # ### end Alembic commands ###
