"""create users table

Revision ID: a4ab2b347be9
Revises: 
Create Date: 2026-07-19 17:25:26.553554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ab2b347be9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('encrypted_password', sa.String(length=128), nullable=False),
    sa.Column('registration_date', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.CheckConstraint('\n            LENGTH(email) >= 5 \n            AND LENGTH(email) <= 30\n            ', name=op.f('ck_users_length_email')),
    sa.CheckConstraint('\n            LENGTH(name) >= 3 \n            AND LENGTH(name) <= 25\n            ', name=op.f('ck_users_length_name')),
    sa.CheckConstraint('\n            LENGTH(surname) >= 3 \n            AND LENGTH(surname) <= 20\n            ', name=op.f('ck_users_length_surname')),
    sa.CheckConstraint('\n            LENGTH(username) >= 5 \n            AND LENGTH(username) <= 20\n            ', name=op.f('ck_users_length_username')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
