"""switch render project to projects table

Revision ID: ad7f1ef7f078
Revises: e926ed845570
Create Date: 2026-07-28 20:22:13.271022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ad7f1ef7f078"
down_revision: Union[str, Sequence[str], None] = "e926ed845570"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("render_project", "projects")

    op.execute(
        "ALTER TABLE projects RENAME CONSTRAINT pk_render_project_id TO pk_projects_id;"
    )
    op.execute(
        "ALTER TABLE projects RENAME CONSTRAINT fk_render_project_user_id_users TO fk_projects_user_id_users;"
    )
    op.execute(
        "ALTER TABLE projects RENAME CONSTRAINT fk_render_project_source_file_id_files TO fk_projects_source_file_id_files;"
    )
    op.execute(
        "ALTER TABLE projects RENAME CONSTRAINT fk_render_project_rendered_file_id_files TO fk_projects_rendered_file_id_files;"
    )
    op.execute(
        "ALTER TABLE projects RENAME CONSTRAINT ck_render_project_length_render_project_name TO ck_projects_length_project_name;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE projects RENAME CONSTRAINT pk_projects_id TO pk_render_project_id;"
    )
    op.execute(
        "ALTER TABLE projects RENAME CONSTRAINT fk_projects_user_id_users TO fk_render_project_user_id_users;"
    )
    op.execute(
        "ALTER TABLE projects RENAME CONSTRAINT fk_projects_source_file_id_files TO fk_render_project_source_file_id_files;"
    )
    op.execute(
        "ALTER TABLE projects RENAME CONSTRAINT fk_projects_rendered_file_id_files TO fk_render_project_rendered_file_id_files;"
    )
    op.execute(
        "ALTER TABLE projects RENAME CONSTRAINT ck_projects_length_project_name TO ck_render_project_length_render_project_name;"
    )

    op.rename_table("projects", "render_project")
    # ### end Alembic commands ###
