"""create renders table

Revision ID: d7e3c4b44fee
Revises: ad7f1ef7f078
Create Date: 2026-07-29 16:08:57.250152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e3c4b44fee'
down_revision: Union[str, Sequence[str], None] = 'ad7f1ef7f078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('denoiser', sa.Boolean(), nullable=False),
    sa.Column('gpu', sa.Boolean(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('\n            height >= 20\n            AND height <= 3840\n            ', name=op.f('ck_renders_value_height')),
    sa.CheckConstraint('\n            samples >= 1\n            AND samples <= 200\n            ', name=op.f('ck_renders_value_samples')),
    sa.CheckConstraint('\n            width >= 20\n            AND width <= 2160\n            ', name=op.f('ck_renders_value_width')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_renders_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_renders_id'))
    )
    op.add_column('projects', sa.Column('render_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_projects_rendered_file_id_files'), 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_render_id_renders'), 'projects', 'renders', ['render_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'rendered_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('rendered_file_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_projects_render_id_renders'), 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_rendered_file_id_files'), 'projects', 'files', ['rendered_file_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'render_id')
    op.drop_table('renders')
    # ### end Alembic commands ###
