"""add render project table

Revision ID: e926ed845570
Revises: 3f72bb9a1698
Create Date: 2026-07-27 15:56:05.205493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e926ed845570"
down_revision: Union[str, Sequence[str], None] = "3f72bb9a1698"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "render_project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column(
            "create_date",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source_file_id", sa.Integer(), nullable=False),
        sa.Column("rendered_file_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("rendering", "completed", name="render_status"),
            server_default="rendering",
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("public", "private", name="project_visibility"),
            server_default="public",
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            LENGTH(name) >= 5 \n            AND LENGTH(name) <= 30\n            ",
            name=op.f("ck_render_project_length_render_project_name"),
        ),
        sa.ForeignKeyConstraint(
            ["rendered_file_id"],
            ["files.id"],
            name=op.f("fk_render_project_rendered_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["files.id"],
            name=op.f("fk_render_project_source_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_render_project_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_render_project_id")),
    )
    op.drop_constraint(op.f("fk_files_user_id_users"), "files", type_="foreignkey")
    op.drop_column("files", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_files_user_id_users"), "files", "users", ["user_id"], ["id"]
    )
    op.drop_table("render_project")

    op.execute("DROP TYPE render_status")
    op.execute("DROP TYPE project_visibility")
    # ### end Alembic commands ###
