name: C++ checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format check
      uses: mrousavy/clang-format-action@v1
      with:
          clang-format-version: '18'
          check-path: 'renderer'
          clang-format-style-path: renderer/.clang-format

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build docker
      run: |
        docker build . --file renderer/Dockerfile --tag renderer --build-arg BUILD_MODE=BOTH --build-arg BUILD_TESTS=ON
    - name: Run tests
      run: |
        docker run --rm --entrypoint /bin/sh renderer -c "cd build && valgrind --leak-check=summary \
         --show-leak-kinds=all \
         --track-origins=yes \
         --error-exitcode=1 ./test"
