name: python-checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: clone git repository
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: install poetry
        run: pip install poetry

      - name: config poetry
        run: poetry config virtualenvs.create false

      - name: install dependencies
        run: poetry install

      - name: run black
        run: black . --check --target-version py313

      - name: run mypy
        run: mypy .

      - name: run ruff
        run: ruff check